### PR TITLE
fix conversions between cv::Mat/cv::MatND and MxArray

### PR DESCRIPTION
**Pull request by amroamroamro**
Following the discussion in #200, this should now correctly handle multi-channels and/or multi-dimensional arrays.

- In order to convert between row-major and column-major ordering of ND-arrays,
the implementation uses `mexCallMATLAB` to do this:

        out = permute(in, ndims(in):-1:1)

  Like I mentioned before, OpenCV doesn't provide an equivalent functionality, so I'm calling MATLAB's `permute` (a powerful function indeed!).

- `cv::transpose` is now used safely, so as to avoid the limitation with the number of channels.

- `cv::split` is not called anymore, which has a [bug](https://github.com/Itseez/opencv/issues/5034) when `mat.dims > 2`.

Now I didn't wanna break the interface, but we probably should remove the `bool transpose` argument from those conversion functions, since we now always return the dimensions in the correct order (whether it's 2d or more).
 
---

To test correctness, take the MEX-function below. It basically converts an input MxArray into Mat and MatND, and then converts them back to output MxArray:

``` cpp
#include "mexopencv.hpp"
using namespace std;
using namespace cv;

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    nargchk(nrhs==1 && nlhs==2);
    Mat mat(MxArray(prhs[0]).toMat());
    MatND matnd(MxArray(prhs[0]).toMatND());
    plhs[0] = MxArray(mat);
    plhs[1] = MxArray(matnd);
}
```

It should handle any combination of dimensions/channels, as long as they are valid (OpenCV has upper limits: `CV_MAX_DIM` and `CV_CN_MAX`, which I believe are defined as 32 and 512 respectively)

``` matlab
C = {...
    rand(4,3);
    rand(4,3,3);
    rand(4,3,10);
    rand(5,4,3,2);
    rand(6,5,4,3,2,1,1);
};
for i=1:numel(C)
    m = C{i};
    [mat,matnd] = testMxArray(m);
    assert(isequal(m,mat,matnd))
end
```

### CODE REVIEW

**Comment by amroamroamro** [comment]
I haven't paid much attention to the case when there are 0-sized dimensions in there, I guess the assertion would fail...

Do you think we should care about that, or can we be sloppy and simply return a 0x0 array?

**Comment by kyamagu** [comment]
@amroamroamro Hmm, that's right. ND array with zero-dimension, for example, `rand(0,5,0,3,0,1,1)`, can easily fail the assertion. The fundamental issue here is that `cv::Mat` does not work as expected. I don't know what would be the most robust solution for this...

Apart from that, we definitely need a test suite for MxArray. Maybe we should add `test/testMxArray.m` and `test/testMxArray_.cpp`?

**Comment by amroamroamro** [comment]
I'm also not sure about the zero-dimension thing, perhaps we can revisit it later... For now we just check with `isempty` in MATLAB and `Mat::empty()` in C++ to catch any zero dimensions.

I like the idea of having a test suite for MxArray. I'm thinking we create a nested namespace, something like:

- `+cv/+test/test1.m`, ...
- `+cv/+test/private/test1_.mex*`, ...
- `src/+cv/+test/private/test1_.cpp`, ...

This should be easier to integrate with the existing build scripts (make.m and makefile) without too much change.

Also I've been meaning to ask, how do you feel about using MATLAB's builtin [unit testing framework](http://www.mathworks.com/help/matlab/matlab-unit-test-framework.html)? It was introduced back in R2013a, and has some nice features we can use (stuff like fixtures, parameterized tests, better reports, all kinds of assertion functions, etc..)
Obviously older versions (and Octave) won't be able to run the tests, but this is only a dev-dependency, so won't affect using mexopencv itself.
If not, we can certainly stick with the existing solution, it's just more convenient to use that framework :)

**Comment by kyamagu** [comment]
@amroamroamro Yes, we can have empty as a special case for now. Hope it doesn't really break any use case... At least the current PR doesn't produce additional failure. I'll test a few more and merge later.

Yep, I am aware of the Mathworks unittest framework. The biggest hassle is a major rewrite to the existing test cases. If that is okay, go ahead with that. The `+test` namespace sounds a good idea also. Either way, testing seems essential here.

Not much relevant here, but another thing Mathworks recently introduced is their own [mexOpenCV](http://www.mathworks.com/help/vision/ug/opencv-interface.html). I haven't checked how they convert data, but that can be a good reference implementation.

**Comment by amroamroamro** [comment]
I've looked into MathWorks' interface for OpenCV (part of the CVST toolbox), but I'm not sure how helpful it is to us... It's provided in binary form only (a header file `opencvmex.hpp` containing only declarations along with a DLL shared library `libmwocvmex.dll` and an import lib `libmwocvmex.lib`), the source implementation is not distributed :(

Besides, their conversion functions *only support images* (i.e they return 2-dim `cv::Mat` with one or more channels):
- `ocvMxArrayToMat_XXX` handles MxNxD mxArray for any sizes of M, N, and D, converting column-major to row-major order (i.e doing a transpose on a 2d mat with multi-channels).
- `ocvMxArrayToImage_XXX` handles only MxNx1 and MxNx3 mxArray like the previous function, but also flips the channels order for color images (RGB->BGR). It's only intended for 1-/3-channels and will drop the extra ones if you pass more than three.

*ND-arrays are not supported* by these functions.  I did a quick test, and they will simply take the first slice, as in `arr(:,:,:,1,1,1,...)`, if you pass it an nd-array.

Same thing applies in the other direction wih `ocvMxArrayFromImage_XXX` and `ocvMxArrayFromMat_XXX`. If you pass them an n-dims cv::Mat, they will only take the first 2 dims (with whatever number of channels), the rest of the dimensions are dropped.

Here is a quick test I played with:

``` cpp
#include "opencvmex.hpp"    // MathWorks vision toolbox
using namespace cv;

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[])
{
    CV_Assert(nrhs==1 && nlhs<=1);
    CV_Assert(mxIsUint8(prhs[0]));
    Mat m;
    ocvMxArrayToMat_uint8(prhs[0], m);
    plhs[0] = ocvMxArrayFromMat_uint8(m);

/*
    int dims[] = {7,6,5,4};
    Mat m(4, dims, CV_8UC3, Scalar(1,2,3));
    plhs[0] = ocvMxArrayFromMat_uint8(m);  // returns 7x6x3 (7x6 mat with 3-channels)
*/
}

```

``` matlab
>> mexOpenCV testMWOCV.cpp
>> x = randi(255, [5,4,3], 'uint8');  % try different sizes here
>> xx = testMWOCV(x);
>> whos x xx; assert(isequal(x,xx))
```

In fact I just found a bug in their implementation! Calling `testMWOCV(zeros([2,2,513],'uint8'))` will crash MATLAB :) (max number of channels is 512)

**Comment by kyamagu** [comment]
@amroamroamro I see, Mathworks implementation is useless.

I've checked the PR in Ubuntu 14.04 64-bit + Matlab R2014a, now I am left with `TestDTrees.test_1` and `TestTransform.test_3` when `d=3`. Do you get the same?

```
Error using TestTransform.test_3 (line 50)
Assertion failed.

Error in UnitTest.all (line 58)
                        feval([class_name,'.',m{:}]);

Error in UnitTest (line 31)
                UnitTest.all(class_name);

FAIL
```

**Comment by amroamroamro** [comment]
hmm no, all tests pass for me (excluding cv.DTrees.train for now)... I'm running Win10 x64 + R2015a + VS2013.

Do you mind inspect the result by placing a breakpoint on the failed assert in `TestTransform.test_3`? Perhaps it's just a floating-point error, and we should simply relax the check to use something like `assert(norm(dst-dst2) < 1e-6)` instead of an exact equality.

**Comment by kyamagu** [comment]
@amroamroamro Right, it was the numerical precision. Fixed the equality test:

    assert(isequal(dst, dst2));

to

    assert(isequal(size(dst), size(dst2)) && all(abs(dst(:) - dst2(:)) < 1e-9));

in the merge.

**Pull request merged**
