### PR TITLE
More OpenCV 3.0 updates

### PR DESCRIPTION
**Pull request by amroamroamro**
This is a another batch of updates for the v3.0 branch.

I compiled against the [final 3.0.0 release](http://opencv.org/opencv-3-0.html) of both `opencv` and `opencv_contrib`.

Excluding the classes `ERTrees` and `GBTrees` that were removed, all the unit-tests now pass. The only failing test I haven't figured out concerns `cv::ml::DTrees::train` which seems to have a bug in OpenCV (it keeps throwing `std::length_error` exceptions!).

---

I tried to keep the commits history readable, so one should be able to follow along to review the list of modifications. Here is a quick summary:

- removed some old function-form files in favor of the new class-form (ORB, MSER, ..)
- updated many functions mainly in `core` and `imgproc` modules
- I would say `features2d` and `xfeatures2d` are complete
- added a number of new functions (optimization functions, LDA, ...)
- add a few sample demos for various functions

Also `MxArray` class received some attention, the highlights:
- updated doxygen comments
- use `mwSize` and `mwIndex` where appropriate
- sprinkle `const` on the code
- new methods: `isNull`, `toFloat`, ..
- improve performance of `::toVector<T>` for primitives
- some new conversion functions for vector of stuff and vector of vector of stuff
- add support for `Vec<T,n>` and `Matx<T,m,n>`

Next thing I'm working is the `ml` and `calib3d` modules, but that's for another pull request :)

### CODE REVIEW

**Comment by kyamagu** [comment]
@amroamroamro Big thanks! Now that v3.0 final is released, maybe at some point we should make v3.0 the master branch and move the current master to v2.4.

**Comment by amroamroamro** [comment]
@kyamagu: I think we can do that, we just need to update the README file to reflect the move.

**Comment by kyamagu** [comment]
@amroamroamro Alright, now the master branch is the stable branch for v3.0. I will keep the v3.0 branch for development.

**Comment by amroamroamro** [comment]
@kyamagu: that's great, thanks! From now on do you want us to send pull requests to `v3.0` or `master`?

I ask because `v3.0` branch is behind by one commit at the moment, so perhaps it should be advanced to `master` (fast-forward merge I mean) to keep the history tree pretty if we were to commit to it.

**Comment by kyamagu** [comment]
@amroamroamro Sorry, didn't notice that commit, now in sync

**Pull request merged**
