### PR TITLE
Added hability to build on Octave

### PR DESCRIPTION
**Pull request by rafaelgm**
- Changed make.m to make it possible to build on Octave
- Disabled __pragma(warning(suppress:4127)) on MinGW (it was raising an error when building)

### CODE REVIEW

**Comment by rafaelgm** [comment]
I think I made a mistake when creating this pull request! Can anyone help me, please?

**Comment by amroamroamro** [comment]
You don't want merge into `master`.

---

Also can you hold off committing to `v3.0` branch for a bit, I have a rather big pull request I'm preparing, and I'd rather we avoid merge conflicts... I'm already removing those `__pragma` I left by mistake and shuffling things around :)

**Comment by rafaelgm** [comment]
@amroamroamro Ok, I'll wait for your changes. After that I can submit my modified make.m to make it possible to build the v3.0 branch with Octave. Anyway, did you make any changes to this file? If that's the case, perhaps the best idea will be for me to wait for your changes and then modify the new make.m.

**Comment by amroamroamro** [comment]
@rafaelgm: Thanks.. No I didn't touch `make.m`, but the others C++ files with the pragma are refactored.

**Pull request closed without merging**
