### PR TITLE
start a test suite for MxArray

### PR DESCRIPTION
**Pull request by amroamroamro**
Following #202, I've started a test suite for MxArray class:

- begin with a couple of tests.
- grouped under `cv.test.*` package.
- add a C++ helper function used as error callback
  (see [`cv::redirectError`](http://docs.opencv.org/3.0.0/db/de0/group__core__utils.html#ga8cd28eccccb695570cdaf86a572d2c0c)), that way OpenCV errors are caught and reported
  back to MATLAB as nicely formatted MEX errors.
- build scripts are updated to compile the C++ tests.
- we're using `matlab.unittest` framework, so this requires a recent
  MATLAB version (R2013b at the least I think).

Once you compile the tests (using the usual mexopencv.make or Makefile), you can run them all in MATLAB as:

    >> run(matlab.unittest.TestSuite.fromPackage('cv.test'))

For now I just wanted to share how the tests would be organized and get feedback. I'll be adding more unit tests to cover many other types of conversions...

### CODE REVIEW

**Comment by kyamagu** [comment]
@amroamroamro For some reason, my MATLAB R2014a on Ubuntu 14.04 cannot find packaged test suites. But the test successfully ran in MATLAB R2015a on the same Ubuntu 14.04. [It looks the fromPackage() is supported since R2014b](http://www.mathworks.com/help/matlab/release-notes.html#zmw57dd0e5672). Yes, packaged tests look beautiful, but I'm a bit worried about requiring R2014b+ to run a test suite. What do you think?

**Comment by amroamroamro** [comment]
oh I missed that. Can you check if the following works in your version instead of `TestSuite.fromPackage`?

``` matlab
% list all functions under cv.test.* package
m = meta.package.fromName('cv.test');
% evaluate them, this returns matlab.unittest.Test objects
tests = cellfun(@feval, {m.FunctionList.Name}, 'UniformOutput',false);
tests = [tests{:}];
% run all tests
run(tests)
```

Either way I'm fine with reverting back to using `UnitTest` class. So far I haven't used anything fancy from `matlab.unittest`, so it's easy to rewrite the tests as static class methods like the existing ones we have. Your call :)

**Comment by kyamagu** [comment]
@amroamroamro It seems there is something else.
```
tests = cellfun(@feval, {m.FunctionList.Name}, 'UniformOutput',false);
Error using feval
Undefined function or variable 'test_MxArray_fromMat'.
```
This is simply missing `cv.test.` in the name.

```
tests = cellfun(@feval, strcat('cv.test.', {m.FunctionList.Name}), 'UniformOutput',false);
Error using functiontests (line 68)
Expected fcns to be nonempty.

Error in cv.test.test_MxArray_fromMat (line 2)
    tests = functiontests(localfunctions);
```
This error happens in R2014a, but not in R2015a. The fundamental issue here is the broken unittest framework in R2014a. In terms of maintenance, we should definitely use the unittest framework. But we need a bit more check against the Matlab bug...

**Comment by amroamroamro** [comment]
My bad, I had done a `import cv.test.*` before, which is why I didn't notice the missing `cv.test.` prefix.

Now I just tested with R2014a, and now I see the problem. It seems `localfunctions` had a bug in that version and won't work from inside packages. If you just call `cv.test.test_MxArray_fromMat` on the command prompt you'll see that `localfunctions` returns an empty cell array... According to the release notes, this was fixed in R2014b:

> **Test suites from packaged functions and scripts**
> The unit testing framework recognizes function-based and script-based tests that are contained within a user-defined package. For more information, see TestSuite.fromPackage and runtests.

The only workaround for R2014a I see is to replace the `localfunctions` call and manually build a cell-array of function-handles with all subfunctions in that file explicitly listed, not pretty nor maintainable! Too bad MathWorks doesn't provide fixes for earlier releases as well..

**Comment by kyamagu** [comment]
@amroamroamro Maybe we can think about class-based testing instead of packaged functions?

**Comment by amroamroamro** [comment]
Good idea. We can use classes-based tests instead of function-based. Although a bit more verbose, it should work and avoid the `localfunctions` bug:

``` matlab
classdef MxArrayTests < matlab.unittest.TestCase
    methods (Test)
        function test1(t)
            t.verifyEqual(1+1, 2);
        end
    end
end
```

To run all tests we use `TestSuite.fromPackage` like before if available, otherwise use:

``` matlab
m = meta.package.fromName('cv.test');
tests = arrayfun(@matlab.unittest.TestSuite.fromClass, m.ClassList, 'Uniform',false);
tests = [tests{:}];
run(tests)
```

**Comment by kyamagu** [comment]
@amroamroamro Thanks, the class-based test works as expected!

**Pull request merged**
