### PR TITLE
Make it possible to build on Octave (Windows)

### PR DESCRIPTION
**Pull request by rafaelgm**
- Tested on Windows using Octave 4.0.0 32-bit (official build) and 64-bit (custom build, using --enable-windows-64) and OpenCV 3.0.0 (final), which was built using MinGW.
- Changed mexopencv.make('clean',true) to delete object files (*.o) MinGW creates on MEXOPENCV_ROOT.

### CODE REVIEW

**Comment by amroamroamro** [comment]
I actually worked on this as well :)
Here is my version:
https://github.com/kyamagu/mexopencv/compare/v3.0...amroamroamro:octave_make

**Comment by rafaelgm** [comment]
@amroamroamro That's nice! :)

**Comment by amroamroamro** [comment]
@rafaelgm : BTW I am trying to test this on my end against Octave 4, but I can't get OpenCV 3 to compile under MinGW-w64;
I'm getting compile errors in the `videoio` module, something to do with "non-virtual destructors".

Got any tips?

**Comment by kyamagu** [comment]
@rafaelgm and @amroamroamro Thanks guys! I cannot test this with my environment now.. Which commit to merge? :)

**Comment by amroamroamro** [comment]
@kyamagu 
Actually can you hold on merging the Octave support. I'm testing it now in Octave 4.0.0, and I discovered some bugs/limitations related to Octave:

- you can't have [local functions in M-class files](http://www.mathworks.com/help/matlab/matlab_oop/specifying-methods-and-functions.html#br2la89).
- [array of objects](http://www.mathworks.com/help/matlab/matlab_oop/initialize-object-arrays.html) are still not supported.
- there is a problem in C++ codes that use  `MxArray(vector<T>)` where `T` is a struct-like type (e.g KeyPoint, DMatch, etc..)
- Plus a few other things I found when running the `UnitTest` class...

I'll create a new pull request as soon as I'm done :)

**Comment by kyamagu** [comment]
@amroamroamro Ok, so there are still a lot of issues in Octave support... Sure, please take time to debug issues. Thanks

**Comment by amroamroamro** [comment]
@rafaelgm Octave fixes were merged into master.

**Comment by amroamroamro** [comment]
@kyamagu
this PR is now outdated and mostly redundant (Octave support is already implemented).
Should be safe to close.

**Comment by kyamagu** [comment]
@amroamroamro Thanks!

**Pull request closed without merging**
