### PR TITLE
OpenCV 3.2.0

### PR DESCRIPTION
**Pull request by amroamroamro**
update to latest stable version of opencv and opencv_contrib, 3.2.0

### CODE REVIEW

**Comment by amroamroamro** [comment]
hmm, the failures in the [Travis build](https://travis-ci.org/kyamagu/mexopencv/builds/210561634) are all coming from tests using the builtin `imread` function in Octave (something not right with its GraphicsMagick library dependency):
```
error: /usr/lib/x86_64-linux-gnu/octave/4.0.2/oct/x86_64-pc-linux-gnu/__magick_read__.oct:
failed to load: libGraphicsMagick++.so.3: cannot open shared object file: No such file or directory
```
Good news is that this has nothing to do with my PR, mexopencv, OpenCV, or MATLAB.
(the AppVeyor build passed all tests, although it's using the latest Octave 4.2.1, not 4.0.2).

Now I just have to figure out how to how to fix it for Travis.. I guess I'll have to debug this in a VM :(
@kyamagu any idea what's wrong?

**Comment by kyamagu** [comment]
@amroamroamro Is `export OCT_IMAGE=no` in travis yml relevant? A quick google search finds [octave bug](https://lists.gnu.org/archive/html/octave-maintainers/2015-07/msg00199.html), but not sure if simply installing graphicsmagick++ via apt-get solves the issue. This is clearly an octave bug, though.

    apt-get install libgraphicsmagick++3

**Comment by amroamroamro** [comment]
> Is export OCT_IMAGE=no in travis yml relevant?

I don't think so. [`imread`](https://www.gnu.org/software/octave/doc/interpreter/Loading-and-Saving-Images.html#XREFimread) is part of core Octave, and not related to the [image](https://octave.sourceforge.io/image/) package. The reason I had it disabled was because the [PPA](https://launchpad.net/~octave/+archive/ubuntu/stable?field.series_filter=precise) didn't have a precompiled version for Precise, and it requires a C++11 compiler to build it from source (gcc-4.6 failed if I remember correctly).

**Comment by amroamroamro** [comment]
>  not sure if simply installing graphicsmagick++ via apt-get solves the issue

It should already be installed along with Octave as dependency. Checking the build log confirms this:
```
$ sudo apt-get install -y octave liboctave-dev
The following NEW packages will be installed:
  ... libgraphicsmagick++3 libgraphicsmagick3 ...

$ dpkg -s octave liboctave-dev
Package: octave
Status: install ok installed
...
Version: 4.0.2-1ubuntu5~octave~precise2
...
Depends: ..., libgraphicsmagick++3, libgraphicsmagick3 (>= 1.3.5), ...
...
```

Interestingly I downloaded the build log file and compared it against the log from the last successful build. It seems GraphicsMagick library was updated at some point. All other dependencies are the same version. Perhaps the new lib version is incompatible with the precompiled Octave version installed from the PPA, and needs to be rebuilt?

```diff
--- old.log
+++ new.log
@@ @@
 Selecting previously unselected package libgraphicsmagick3.
-Unpacking libgraphicsmagick3 (from .../libgraphicsmagick3_1.3.12-1.1build1_amd64.deb) ...
+Unpacking libgraphicsmagick3 (from .../libgraphicsmagick3_1.3.25-rwky1~precise_amd64.deb) ...
 Selecting previously unselected package libgraphicsmagick++3.
-Unpacking libgraphicsmagick++3 (from .../libgraphicsmagick++3_1.3.12-1.1build1_amd64.deb) ...
+Unpacking libgraphicsmagick++3 (from .../libgraphicsmagick++3_1.3.25-rwky1~precise_amd64.deb) ...
 Selecting previously unselected package libhdf5-serial-dev.
 Unpacking libhdf5-serial-dev (from .../libhdf5-serial-dev_1.8.4-patch1-3ubuntu2_amd64.deb) ...
 Selecting previously unselected package liblapack-dev.
 Unpacking liblapack-dev (from .../liblapack-dev_3.3.1-1_amd64.deb) ...
 Selecting previously unselected package libmagick++4.
-Unpacking libmagick++4 (from .../libmagick++4_8%3a6.6.9.7-5ubuntu3.6_amd64.deb) ...
+Unpacking libmagick++4 (from .../libmagick++4_8%3a6.6.9.7-5ubuntu3.8_amd64.deb) ...
@@ @@
 Setting up libglpk0 (4.45-1build1) ...
-Setting up libgraphicsmagick3 (1.3.12-1.1build1) ...
-Setting up libgraphicsmagick++3 (1.3.12-1.1build1) ...
+Setting up libgraphicsmagick3 (1.3.25-rwky1~precise) ...
+Setting up libgraphicsmagick++3 (1.3.25-rwky1~precise) ...
 Setting up libhdf5-serial-dev (1.8.4-patch1-3ubuntu2) ...
 Setting up liblapack-dev (3.3.1-1) ...
 update-alternatives: using /usr/lib/lapack/liblapack.so to provide /usr/lib/liblapack.so (liblapack.so) in auto mode.
-Setting up libmagick++4 (8:6.6.9.7-5ubuntu3.6) ...
+Setting up libmagick++4 (8:6.6.9.7-5ubuntu3.8) ...
 Setting up libqhull5 (2009.1-3ubuntu1) ...
```

**Comment by amroamroamro** [comment]
I tried to replicate this locally in a VM running Ubuntu 14.04 LTS.
I compiled OpenCV 3.2.0 from source, installed Octave 4 from the same PPA, and built mexopencv with above PR against them.
But it all ran without any problems. Now I'm thinking it has to do with Ubuntu 12.04 vs 14.04..
I just pushed a change to choose Trusty (14.04) in Travis instead of the default Precise (12.04).
Let's see if that works :)

**Comment by amroamroamro** [comment]
no luck, `imread` still fails 😕 
And the weird thing, it works in my local VM, same versions as far as I can tell...

@kyamagu 
I say we merge the PR, those failure are unrelated. I'll have to investigate it later, maybe ask for help of the octave mailing list..

**Comment by kyamagu** [comment]
@amroamroamro Alright, go ahead and merge first. This could be due to Travis, because Travis customizes VM environment and some packages are not exactly the same even if the platform is Ubuntu. Octave is buggy also...

**Comment by kyamagu** [comment]
@amroamroamro Thanks!

**Comment by amroamroamro** [comment]
I also updated the instructions in the wiki, now targeting opencv 3.2.0

**Pull request merged**
